#!/usr/bin/env zsh

# Some directory listing with colors
alias sl=ls
alias ls='ls -G'        # Compact view, show colors
alias la='ls -AF'       # Compact view, show hidden
alias ll='ls -al'
alias l='ls -a'
alias l1='ls -1'

# because I'm to lazy to write vim
alias v='nvim'
alias n="nvim"
alias s="sudo"
 # incase i forget how to clear
  alias c='clear'
  alias k='clear'
  alias cls='clear'

